//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
        }
    
        public int sanpham_id { get; set; }
        public string sanpham_name { get; set; }
        public Nullable<int> gia_sanpham { get; set; }
        public Nullable<int> soluong_sp { get; set; }
        public string theloai_id { get; set; }
        public string hinhanh_sp { get; set; }
        public string hinhanh_sp1 { get; set; }
        public string hinhanh_sp3 { get; set; }
        public string hinhanh_sp4 { get; set; }
        public string kichthuoc_hinhanh { get; set; }
        public string camera_truoc { get; set; }
        public string camera_sau { get; set; }
        public string he_dieu_hanh { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string bo_nho_trong { get; set; }
        public string the_nho { get; set; }
        public string sim { get; set; }
        public string ket_noi { get; set; }
        public string pin { get; set; }
        public string chuthich { get; set; }
        public Nullable<int> moi { get; set; }
        public Nullable<int> style { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual theloaisp theloaisp { get; set; }
    }
}
